### ISSUE TITLE
V9 Migration PoC

### ISSUE THREAD

**Issue by jianhandev** [zhaojj2209/teammates#26]
This issue keeps track of all the tasks related to the PoC:
- [x] Setting up ORM (#11)
- [x] Implement CRUD on Course and Instructor with transactions (#13 and #15)
- [x] Implement the logic layer based on the interoperability design laid out [here](https://docs.google.com/document/d/17bc3q670y1YUMU6IwrZ-9BLZwALhVFdJR2ugMhPZJ5g/edit) ( #12)
- [x] Demonstrate how integration and system level tests can be set up with the new database ( #18)
- [x] Demonstrate how database migrations will be done when the data model changes e.g. adding or removing of fields (#16)
